- hosts: nekobasu
  become: true
  remote_user: connor
  tasks:
    - name: Install packages
      apt: name={{item}}
      with_items:
        - docker.io
        - python-pip
        - neovim
        - vlc
        - x264
        - tmux
        - gnupg2
        - curl
        - ack
        - rsnapshot
        - git
        - virtualbox-qt
    
    - name: Install docker-compose
      pip: name=docker-compose
    - name: Add connor to docker group
      user: name=connor
            group=connor
            groups=docker
            append=yes
  roles:
    - role: fubarhouse.rust
      become: true
      vars:
        rust_update: true
        shell_profiles:
        - .profile
        
