- hosts: localhost
  become: true
  remote_user: connor
  tasks:
    - name: Install packages
      apt: name={{item}}
      with_items:
        - docker.io
        - python-pip
        - neovim
        - vlc
        - x264
        - tmux
        - gnupg2
        - curl
        - ack
        - rsnapshot
        - git
        - virtualbox-qt
        - yubico-piv-tool
        - libykpiv-dev
  roles:
    - role: fubarhouse.golang
      vars:
        go_version: 1.13.9
        GOPATH: /home/connor/go
        GOROOT: /usr/go
        GOPROXY: https://proxy.golang.org
        GO111MODULE: "on"
        get_get:
          - name: mkcert
            url: github.com/FiloSottile/mkcert
          - name: goimports
            url: golang.org/x/tools/cmd/goimports
          - name: golint
            url: golang.org/x/lint/golint
          - name: petrify
            url: gophers.dev/cmds/petrify/v5
          - name: fields
            url: gophers.dev/cmds/fields
          - name: envy
            url: gophers.dev/cmds/envy
          - name: prealloc
            url: github.com/alexkohler/prealloc
          - name: act
            url: github.com/nektos/act
          - name: yubikey-agent
            url: github.com/FiloSottile/yubikey-agent
        golang_shell_profile: /home/connor/.profile
    
    - name: Install docker-compose
      pip: name=docker-compose
    - name: Add connor to docker group
      user: name=connor
            group=connor
            groups=docker
            append=yes
  roles:
    - role: fubarhouse.rust
      become: true
      vars:
        rust_update: true
        shell_profiles:
        - .profile
        
